In [2]:
read_file = open(file_name, "r")

NameError: name 'file_name' is not defined

In [3]:
ls

LICENSE  program_B.Rproj  raw_data/  rstudio_programB.R  Untitled.ipynb


In [13]:
cd ..

/home/anna/Desktop/program_B


In [5]:
ls

sampleA.txt  sampleBprime.txt  sampleB.txt


In [36]:
def read_file(txt_file):
    """read in .txt files"""
    with open(txt_file, 'r') as f:
        print(f)
        

In [33]:
ls

sampleA.txt  sampleBprime.txt  sampleB.txt


In [34]:
txt_file = 'sampleA.txt'

In [37]:
read_file(txt_file)

<_io.TextIOWrapper name='sampleA.txt' mode='r' encoding='UTF-8'>


In [57]:
file_handle = open(txt_file, 'r')

In [56]:
for line in file_handle:
    print(line)
    print([token.strip() for token in line.split("\t")])

gene	sampleA

['gene', 'sampleA']
EfM3.000010	21

['EfM3.000010', '21']
EfM3.000020	63

['EfM3.000020', '63']
EfM3.000030	42

['EfM3.000030', '42']
EfM3.000040	8

['EfM3.000040', '8']
EfM3.000050	206

['EfM3.000050', '206']
EfM3.000060	202

['EfM3.000060', '202']
EfM3.000070	129

['EfM3.000070', '129']
EfM3.000080	89

['EfM3.000080', '89']
EfM3.000090	11

['EfM3.000090', '11']
EfM3.000100	326

['EfM3.000100', '326']
EfM3.000110	149

['EfM3.000110', '149']
EfM3.000120	51

['EfM3.000120', '51']
EfM3.000130	0

['EfM3.000130', '0']
EfM3.000140	5

['EfM3.000140', '5']
EfM3.000150	77

['EfM3.000150', '77']
EfM3.000160	66

['EfM3.000160', '66']
EfM3.000170	120

['EfM3.000170', '120']
EfM3.000180	14

['EfM3.000180', '14']
EfM3.000190	1060

['EfM3.000190', '1060']
EfM3.000200	57

['EfM3.000200', '57']
EfM3.000210	876

['EfM3.000210', '876']
EfM3.000220	1

['EfM3.000220', '1']
EfM3.000230	24

['EfM3.000230', '24']
EfM3.000240	67

['EfM3.000240', '67']
EfM3.000250	4

['EfM3.000250', '4']
EfM3.000

In [58]:
file_handle.readlines()


['gene\tsampleA\n',
 'EfM3.000010\t21\n',
 'EfM3.000020\t63\n',
 'EfM3.000030\t42\n',
 'EfM3.000040\t8\n',
 'EfM3.000050\t206\n',
 'EfM3.000060\t202\n',
 'EfM3.000070\t129\n',
 'EfM3.000080\t89\n',
 'EfM3.000090\t11\n',
 'EfM3.000100\t326\n',
 'EfM3.000110\t149\n',
 'EfM3.000120\t51\n',
 'EfM3.000130\t0\n',
 'EfM3.000140\t5\n',
 'EfM3.000150\t77\n',
 'EfM3.000160\t66\n',
 'EfM3.000170\t120\n',
 'EfM3.000180\t14\n',
 'EfM3.000190\t1060\n',
 'EfM3.000200\t57\n',
 'EfM3.000210\t876\n',
 'EfM3.000220\t1\n',
 'EfM3.000230\t24\n',
 'EfM3.000240\t67\n',
 'EfM3.000250\t4\n',
 'EfM3.000260\t14\n',
 'EfM3.000270\t174\n',
 'EfM3.000280\t6\n',
 'EfM3.000290\t68\n',
 'EfM3.000300\t24\n',
 'EfM3.000310\t85\n',
 'EfM3.000320\t36\n',
 'EfM3.000330\t142\n',
 'EfM3.000340\t107\n',
 'EfM3.000350\t134\n',
 'EfM3.000360\t322\n',
 'EfM3.000370\t147\n',
 'EfM3.000380\t3\n',
 'EfM3.000390\t333\n',
 'EfM3.000400\t237\n',
 'EfM3.000410\t25\n',
 'EfM3.000420\t35\n',
 'EfM3.000430\t314\n',
 'EfM3.000440\t214\n',


In [59]:
d = {}

In [64]:
d['k'] = "12\n"

In [65]:
d

{'k': '12\n'}

In [66]:
d['k'] * 7

'12\n12\n12\n12\n12\n12\n12\n'

In [37]:
handle = open('sampleA.txt') 
next(handle)

'gene\tsampleA\n'

In [40]:
#take .txt files and convert to dictionary form so we can access the values(read counts)
read_count_dict = {}
with open('sampleA.txt') as a:
    next(a) #skipping the header
    for line in a:
        (k, v) = line.split('\t')
        read_count_dict[k.strip()] = int(v.strip())
print(read_count_dict)

{'EfM3.000010': 21, 'EfM3.000020': 63, 'EfM3.000030': 42, 'EfM3.000040': 8, 'EfM3.000050': 206, 'EfM3.000060': 202, 'EfM3.000070': 129, 'EfM3.000080': 89, 'EfM3.000090': 11, 'EfM3.000100': 326, 'EfM3.000110': 149, 'EfM3.000120': 51, 'EfM3.000130': 0, 'EfM3.000140': 5, 'EfM3.000150': 77, 'EfM3.000160': 66, 'EfM3.000170': 120, 'EfM3.000180': 14, 'EfM3.000190': 1060, 'EfM3.000200': 57, 'EfM3.000210': 876, 'EfM3.000220': 1, 'EfM3.000230': 24, 'EfM3.000240': 67, 'EfM3.000250': 4, 'EfM3.000260': 14, 'EfM3.000270': 174, 'EfM3.000280': 6, 'EfM3.000290': 68, 'EfM3.000300': 24, 'EfM3.000310': 85, 'EfM3.000320': 36, 'EfM3.000330': 142, 'EfM3.000340': 107, 'EfM3.000350': 134, 'EfM3.000360': 322, 'EfM3.000370': 147, 'EfM3.000380': 3, 'EfM3.000390': 333, 'EfM3.000400': 237, 'EfM3.000410': 25, 'EfM3.000420': 35, 'EfM3.000430': 314, 'EfM3.000440': 214, 'EfM3.000450': 8, 'EfM3.000460': 42, 'EfM3.000470': 38, 'EfM3.000480': 78, 'EfM3.000490': 127, 'EfM3.000500': 125, 'EfM3.000510': 228, 'EfM3.000520': 4

In [41]:
read_count_dict.values()

dict_values([21, 63, 42, 8, 206, 202, 129, 89, 11, 326, 149, 51, 0, 5, 77, 66, 120, 14, 1060, 57, 876, 1, 24, 67, 4, 14, 174, 6, 68, 24, 85, 36, 142, 107, 134, 322, 147, 3, 333, 237, 25, 35, 314, 214, 8, 42, 38, 78, 127, 125, 228, 416, 626, 207, 12, 168, 524, 102, 101, 207, 344, 116, 109, 1, 163, 18, 285, 1, 295, 199, 204, 366, 45, 139, 41, 103, 314, 66, 142, 157, 24, 28, 22, 64, 112, 52, 86, 2, 124, 77, 34, 290, 909, 266, 16, 130, 414, 95, 336, 14])

In [42]:
#get v to be an int not str
dict = {}
with open('sampleA.txt') as a:
    for line in a:
        (k, v) = line.split('\t')
        #dict[k.strip()] = int(v.strip())
        print "k:" + str(k.strip()) + "v:" + str(v.strip()) #never mind. sorted in the cell above. this line is python2

SyntaxError: invalid syntax (<ipython-input-42-8151fb44bb2e>, line 7)

In [14]:
v

'sampleA\n'

In [15]:
dict

{}

In [22]:
dict.keys()

dict_keys([])

In [19]:
print 'k:' + str(k.strip()) + 'v:' + str(v.strip())

SyntaxError: invalid syntax (<ipython-input-19-ee255f4a360c>, line 1)

In [62]:
def tsv_to_dict(tsv_file):
    """takes a tsv file and reads it as a dictionary
    tsv_file : input tsv file
    read_count_dict : ouput dictionary
    dictionary keys : gene names
    dictionary values : read count (int)
    """
    read_count_dict = {} #initialise dictionary
    with open(tsv_file) as f:
        next(f) #skipping the header
        for line in f:
            (k, v) = line.split('\t')
            read_count_dict[k.strip()] = int(v.strip())
    return(read_count_dict)

In [47]:
tsv_file = 'sampleA.txt'

In [50]:
read_count_dict = 'practice_dictionary'

In [51]:
read_count_dict = {} #initialise dictionary
with open(tsv_file) as f:
    next(f) #skipping the header
    for line in f:
        (k, v) = line.split('\t')
        read_count_dict[k.strip()] = int(v.strip())
print(read_count_dict)

{'EfM3.000010': 21, 'EfM3.000020': 63, 'EfM3.000030': 42, 'EfM3.000040': 8, 'EfM3.000050': 206, 'EfM3.000060': 202, 'EfM3.000070': 129, 'EfM3.000080': 89, 'EfM3.000090': 11, 'EfM3.000100': 326, 'EfM3.000110': 149, 'EfM3.000120': 51, 'EfM3.000130': 0, 'EfM3.000140': 5, 'EfM3.000150': 77, 'EfM3.000160': 66, 'EfM3.000170': 120, 'EfM3.000180': 14, 'EfM3.000190': 1060, 'EfM3.000200': 57, 'EfM3.000210': 876, 'EfM3.000220': 1, 'EfM3.000230': 24, 'EfM3.000240': 67, 'EfM3.000250': 4, 'EfM3.000260': 14, 'EfM3.000270': 174, 'EfM3.000280': 6, 'EfM3.000290': 68, 'EfM3.000300': 24, 'EfM3.000310': 85, 'EfM3.000320': 36, 'EfM3.000330': 142, 'EfM3.000340': 107, 'EfM3.000350': 134, 'EfM3.000360': 322, 'EfM3.000370': 147, 'EfM3.000380': 3, 'EfM3.000390': 333, 'EfM3.000400': 237, 'EfM3.000410': 25, 'EfM3.000420': 35, 'EfM3.000430': 314, 'EfM3.000440': 214, 'EfM3.000450': 8, 'EfM3.000460': 42, 'EfM3.000470': 38, 'EfM3.000480': 78, 'EfM3.000490': 127, 'EfM3.000500': 125, 'EfM3.000510': 228, 'EfM3.000520': 4

In [64]:
res = tsv_to_dict('sampleA.txt')

In [65]:
res['EfM3.000650']

163

In [66]:
res_b = tsv_to_dict('sampleB.txt')

In [67]:
res_b['EfM3.000650']

100

In [102]:
#write a function to iterate over every value from tsv_file_a and tsv_file_b (use dict.values)
#and find the difference between the read counts for every gene
def read_counts_diff(dict_a, dict_b): #some code modified from stackoverflow @slearner
    """write this properly from the # above when I know exactly what I'm talking about"""
    #iterate over every key with .keys
    output_dict = {}
    for k in dict_a.keys():
        if k in dict_b.keys():
            output_dict[k] = abs(dict_a[k] - dict_b[k])
    return(output_dict) #now what I actually want to put in dictionary is chi squared results

In [106]:
read_counts_diff(res, res_b)

{'EfM3.000010': 13,
 'EfM3.000020': 49,
 'EfM3.000030': 35,
 'EfM3.000040': 5,
 'EfM3.000050': 165,
 'EfM3.000060': 125,
 'EfM3.000070': 33,
 'EfM3.000080': 34,
 'EfM3.000090': 6,
 'EfM3.000100': 211,
 'EfM3.000110': 97,
 'EfM3.000120': 39,
 'EfM3.000130': 0,
 'EfM3.000140': 4,
 'EfM3.000150': 37,
 'EfM3.000160': 39,
 'EfM3.000170': 95,
 'EfM3.000180': 9,
 'EfM3.000190': 929,
 'EfM3.000200': 29,
 'EfM3.000210': 747,
 'EfM3.000220': 1,
 'EfM3.000230': 19,
 'EfM3.000240': 35,
 'EfM3.000250': 1,
 'EfM3.000260': 4,
 'EfM3.000270': 111,
 'EfM3.000280': 5,
 'EfM3.000290': 22,
 'EfM3.000300': 6,
 'EfM3.000310': 46,
 'EfM3.000320': 22,
 'EfM3.000330': 85,
 'EfM3.000340': 71,
 'EfM3.000350': 69,
 'EfM3.000360': 122,
 'EfM3.000370': 97,
 'EfM3.000380': 13,
 'EfM3.000390': 232,
 'EfM3.000400': 92,
 'EfM3.000410': 21,
 'EfM3.000420': 26,
 'EfM3.000430': 281,
 'EfM3.000440': 67,
 'EfM3.000450': 3,
 'EfM3.000460': 10,
 'EfM3.000470': 17,
 'EfM3.000480': 42,
 'EfM3.000490': 85,
 'EfM3.000500': 82,
 '

In [149]:
#write a function to iterate over every value from tsv_file_a and tsv_file_b (use dict.values)
#and find the difference between the read counts for every gene
#***don't use this bit for final script
def read_counts_diff(dict_a, dict_b): #some code modified from stackoverflow @slearner
    """write this properly from the # above when I know exactly what I'm talking about"""
    #iterate over every key with .keys
    output_dict = {}
    for k in dict_a.keys():
        if k in dict_b.keys():
            output_dict[k] = abs(dict_a[k] - dict_b[k])
    return(output_dict) #now what I actually want to put in dictionary is chi squared results

In [117]:
from scipy.stats import chi2_contingency
import numpy as np

In [118]:
chi2_contingency

<function scipy.stats.contingency.chi2_contingency>

In [121]:
from scipy.stats import chi2_contingency
obs = np.array([[10, 10, 20], [20, 20, 20]]) # 2C 3R
t = chi2_contingency(obs) #get data (pvalue?) out we want from output and fit data into contingency

In [125]:
t

(2.7777777777777777, 0.24935220877729622, 2, array([[ 12.,  12.,  16.],
        [ 18.,  18.,  24.]]))

In [127]:
t[1]

0.24935220877729622

In [148]:
obs = np.array([[10, 10, 20], [20, 20, 20]]) # 2C 3R
t = chi2_contingency(obs) #get data (pvalue?) out we want from output and fit data into contingency
if t[1] < 0.05:
    print("significant")
else:
    print("not significant")

not significant


In [145]:
n = np.array

In [150]:
#s1_gi
res.keys()

dict_keys(['EfM3.000010', 'EfM3.000020', 'EfM3.000030', 'EfM3.000040', 'EfM3.000050', 'EfM3.000060', 'EfM3.000070', 'EfM3.000080', 'EfM3.000090', 'EfM3.000100', 'EfM3.000110', 'EfM3.000120', 'EfM3.000130', 'EfM3.000140', 'EfM3.000150', 'EfM3.000160', 'EfM3.000170', 'EfM3.000180', 'EfM3.000190', 'EfM3.000200', 'EfM3.000210', 'EfM3.000220', 'EfM3.000230', 'EfM3.000240', 'EfM3.000250', 'EfM3.000260', 'EfM3.000270', 'EfM3.000280', 'EfM3.000290', 'EfM3.000300', 'EfM3.000310', 'EfM3.000320', 'EfM3.000330', 'EfM3.000340', 'EfM3.000350', 'EfM3.000360', 'EfM3.000370', 'EfM3.000380', 'EfM3.000390', 'EfM3.000400', 'EfM3.000410', 'EfM3.000420', 'EfM3.000430', 'EfM3.000440', 'EfM3.000450', 'EfM3.000460', 'EfM3.000470', 'EfM3.000480', 'EfM3.000490', 'EfM3.000500', 'EfM3.000510', 'EfM3.000520', 'EfM3.000530', 'EfM3.000540', 'EfM3.000550', 'EfM3.000560', 'EfM3.000570', 'EfM3.000580', 'EfM3.000590', 'EfM3.000600', 'EfM3.000610', 'EfM3.000620', 'EfM3.000630', 'EfM3.000640', 'EfM3.000650', 'EfM3.000660',

In [152]:
np.arange(25).reshape((5, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [155]:
dict_a = res
dict_b = res_b

In [156]:
for k in dict_a.keys():
        if k in dict_b.keys():
            print(dict_a[k], dict_b[k]) #s1_gi , s2_gi

21 8
63 14
42 7
8 3
206 41
202 77
129 96
89 55
11 5
326 115
149 52
51 12
0 0
5 1
77 40
66 27
120 25
14 5
1060 131
57 28
876 129
1 2
24 5
67 32
4 3
14 10
174 63
6 1
68 46
24 18
85 39
36 14
142 57
107 36
134 65
322 200
147 50
3 16
333 101
237 145
25 4
35 9
314 33
214 147
8 5
42 32
38 21
78 36
127 42
125 43
228 128
416 259
626 247
207 103
12 8
168 51
524 112
102 37
101 74
207 63
344 74
116 63
109 37
1 0
163 100
18 8
285 186
1 1
295 92
199 74
204 56
366 138
45 13
139 104
41 30
103 49
314 103
66 32
142 150
157 41
24 7
28 20
22 22
64 29
112 60
52 29
86 32
2 9
124 73
77 20
34 19
290 104
909 266
266 74
16 1
130 29
414 226
95 53
336 136
14 9


In [159]:
t_a = sum(dict_a.values()) #s1_t

In [160]:
t_b = sum(dict_b.values()) #s2_t

In [166]:
t_a

15300

In [167]:
t_b

5797

In [171]:
#if the gene name is the same in sample a, sample b, calculate total sample read count - gene x read count
for gene in dict_a.keys():
        if gene in dict_b.keys():
            print((t_a - dict_a[gene]),(t_b - dict_b[gene])) #s1_'gi , s2_'gi

15279 5789
15237 5783
15258 5790
15292 5794
15094 5756
15098 5720
15171 5701
15211 5742
15289 5792
14974 5682
15151 5745
15249 5785
15300 5797
15295 5796
15223 5757
15234 5770
15180 5772
15286 5792
14240 5666
15243 5769
14424 5668
15299 5795
15276 5792
15233 5765
15296 5794
15286 5787
15126 5734
15294 5796
15232 5751
15276 5779
15215 5758
15264 5783
15158 5740
15193 5761
15166 5732
14978 5597
15153 5747
15297 5781
14967 5696
15063 5652
15275 5793
15265 5788
14986 5764
15086 5650
15292 5792
15258 5765
15262 5776
15222 5761
15173 5755
15175 5754
15072 5669
14884 5538
14674 5550
15093 5694
15288 5789
15132 5746
14776 5685
15198 5760
15199 5723
15093 5734
14956 5723
15184 5734
15191 5760
15299 5797
15137 5697
15282 5789
15015 5611
15299 5796
15005 5705
15101 5723
15096 5741
14934 5659
15255 5784
15161 5693
15259 5767
15197 5748
14986 5694
15234 5765
15158 5647
15143 5756
15276 5790
15272 5777
15278 5775
15236 5768
15188 5737
15248 5768
15214 5765
15298 5788
15176 5724
15223 5777
15266 5778

In [170]:
import numpy as np
import pandas as pd
import os

In [184]:
k

'EfM3.001000'

In [173]:
obs #first make this into 2x2, then try get just 'k' gene into array form, then do chisquared for just k gene

array([[10, 10, 20],
       [20, 20, 20]])

In [192]:
twobytwo = np.array([[dict_a[k], (t_a - dict_a[gene])], [dict_b[k], (t_b - dict_b[gene])]])

In [193]:
twobytwo

array([[   14, 15286],
       [    9,  5788]])

In [185]:
dict_a[k]

14

In [186]:
dict_b[k]

9

In [187]:
dict_a

{'EfM3.000010': 21,
 'EfM3.000020': 63,
 'EfM3.000030': 42,
 'EfM3.000040': 8,
 'EfM3.000050': 206,
 'EfM3.000060': 202,
 'EfM3.000070': 129,
 'EfM3.000080': 89,
 'EfM3.000090': 11,
 'EfM3.000100': 326,
 'EfM3.000110': 149,
 'EfM3.000120': 51,
 'EfM3.000130': 0,
 'EfM3.000140': 5,
 'EfM3.000150': 77,
 'EfM3.000160': 66,
 'EfM3.000170': 120,
 'EfM3.000180': 14,
 'EfM3.000190': 1060,
 'EfM3.000200': 57,
 'EfM3.000210': 876,
 'EfM3.000220': 1,
 'EfM3.000230': 24,
 'EfM3.000240': 67,
 'EfM3.000250': 4,
 'EfM3.000260': 14,
 'EfM3.000270': 174,
 'EfM3.000280': 6,
 'EfM3.000290': 68,
 'EfM3.000300': 24,
 'EfM3.000310': 85,
 'EfM3.000320': 36,
 'EfM3.000330': 142,
 'EfM3.000340': 107,
 'EfM3.000350': 134,
 'EfM3.000360': 322,
 'EfM3.000370': 147,
 'EfM3.000380': 3,
 'EfM3.000390': 333,
 'EfM3.000400': 237,
 'EfM3.000410': 25,
 'EfM3.000420': 35,
 'EfM3.000430': 314,
 'EfM3.000440': 214,
 'EfM3.000450': 8,
 'EfM3.000460': 42,
 'EfM3.000470': 38,
 'EfM3.000480': 78,
 'EfM3.000490': 127,
 'EfM3.0

In [194]:
chi2_contingency(twobytwo)

(1.0381116844136888,
 0.30826105115718599,
 1,
 array([[  1.66800967e+01,   1.52833199e+04],
        [  6.31990330e+00,   5.79068010e+03]]))

In [196]:
def read_counts_diff(dict_a, dict_b): #some code modified from stackoverflow @slearner
    """write this properly from the # above when I know exactly what I'm talking about"""
    #iterate over every key with .keys
    output_dict = {}
    for k in dict_a.keys():
        if k in dict_b.keys():
            output_dict[k] = abs(dict_a[k] - dict_b[k]) #chisquare bit goes in here instead of difference
    return(output_dict)

In [197]:
twobytwo = np.array([[dict_a[k], (t_a - dict_a[gene])], [dict_b[k], (t_b - dict_b[gene])]])

In [252]:
def tsv_to_dict(tsv_file): #script from here
    """takes a tsv file and reads it as a dictionary
    tsv_file : input tsv file
    read_count_dict : ouput dictionary
    dictionary keys : gene names
    dictionary values : read count (int)
    """
    read_count_dict = {} #initialise dictionary
    with open(tsv_file) as f:
        next(f) #skipping the header
        for line in f:
            (k, v) = line.split('\t')
            read_count_dict[k.strip()] = int(v.strip())
    return(read_count_dict)

In [253]:
sample_a_dict = tsv_to_dict('sampleA.txt')
sample_b_dict = tsv_to_dict('sampleB.txt')

In [280]:
def read_count_sig(gene, dict_a, dict_b):
#input gene name, dictionaries to look up gene name, do chi square. output tuple of gene name,
#pvalue (keep this in so we can correct for multiple testing later), 'significant/not'
    total_read_count_a = sum(dict_a.values())
    total_read_count_b = sum(dict_b.values())
    for gene in dict_a.keys():
        if gene in dict_b.keys():
            count_a = dict_a[gene]
            count_b = dict_b[gene]
        if (count_a == 0) and (count_b == 0):
            #do something with genes with no read counts
            pass
        else:
            contingency_table = np.array([[count_a, (total_read_count_a - count_a)], [count_b, (total_read_count_b - count_b)]])
            chi2_output = chi2_contingency(contingency_table)        
    return(gene, count_a, count_b, chi2_output[1])

In [281]:
read_count_sig('EfM3.000990', sample_a_dict, sample_b_dict)

('EfM3.001000', 14, 9, 0.30826105115718599)

In [256]:
sample_a_dict = tsv_to_dict('sampleA.txt')
sample_b_dict = tsv_to_dict('sampleB.txt')
gene = 'EfM3.000990'

In [265]:
total_read_count_a = sum(dict_a.values())
total_read_count_b = sum(dict_b.values())
for gene in dict_a.keys():
    if gene in dict_b.keys():
        count_a = dict_a[gene]
        count_b = dict_b[gene]
        if (count_a == 0) and (count_b == 0):
            #do something with genes with no read counts
            pass
        else:
            contingency_table = np.array([[count_a, (total_read_count_a - count_a)], [count_b, (total_read_count_b - count_b)]])
            chi2_output = chi2_contingency(contingency_table)
            print(chi2_output)        

(0.038045381644028806, 0.84535204065759084, 1, array([[  2.10314263e+01,   1.52789686e+04],
       [  7.96857373e+00,   5.78903143e+03]]))
(2.8995013985854552, 0.088606956353931912, 1, array([[    55.84206285,  15244.15793715],
       [    21.15793715,   5775.84206285]]))
(3.651374567474361, 0.056022957147010978, 1, array([[  3.55358582e+01,   1.52644641e+04],
       [  1.34641418e+01,   5.78353586e+03]]))
(0.10404318451941223, 0.7470305681393874, 1, array([[  7.97743755e+00,   1.52920226e+04],
       [  3.02256245e+00,   5.79397744e+03]]))
(14.295303600779491, 0.0001562542349743375, 1, array([[   179.12973409,  15120.87026591],
       [    67.87026591,   5729.12973409]]))
(0.00048532276372567412, 0.98242399105962197, 1, array([[   202.33682514,  15097.66317486],
       [    76.66317486,   5720.33682514]]))
(25.564209312610526, 4.279032399875049e-07, 1, array([[   163.17485898,  15136.82514102],
       [    61.82514102,   5735.17485898]]))
(7.8232892025393577, 0.0051577244478372688, 1,

In [258]:
contingency_table = np.array([[dict_a[gene], (total_read_count_a - dict_a[gene])], [dict_b[gene], (total_read_count_b - dict_b[gene])]])
chi2_output = chi2_contingency(contingency_table)

ValueError: The internally computed table of expected frequencies has a zero element at (0, 0).

In [259]:
dict_b[gene] #this is the source of the valueerror

0

In [263]:
contingency_table

array([[    0, 15300],
       [    0,  5797]])

In [267]:
for g in dict_a.keys():
    if dict_a[g] == 0 and dict_b[g] == 0:
        break

In [268]:
g

'EfM3.000130'

In [269]:
! grep 'EfM3.000130' sampleA.txt

EfM3.000130	0


In [270]:
! grep 'EfM3.000130' sampleB.txt

EfM3.000130	0


In [271]:
np.nan # for missing data or undefined pvalue (exp = 0 and 0)

nan

In [272]:
np.nan < 0.1

False

In [320]:
def read_count_sig(dict_a, dict_b):
#input gene name, dictionaries to look up gene name, do chi square. output tuple of gene name,
#pvalue (keep this in so we can correct for multiple testing later), 'significant/not'
    total_read_count_a = sum(dict_a.values())
    total_read_count_b = sum(dict_b.values())
    for gene in dict_a.keys():
        if gene in dict_b.keys():
            count_a = dict_a[gene]
            count_b = dict_b[gene]
        if (count_a == 0) and (count_b == 0):
            #do something with genes with no read counts
            pass
        else:
            contingency_table = np.array([[count_a, (total_read_count_a - count_a)], [count_b, (total_read_count_b - count_b)]])
            chi2_output = chi2_contingency(contingency_table)
            print(gene, count_a, count_b, chi2_output[1])

In [321]:
read_count_sig(sample_a_dict, sample_b_dict) #store output as 4 lists
#as we need all pvalues first before we can adjust, so putting adjusting within above loop won't work

EfM3.000010 21 8 0.845352040658
EfM3.000020 63 14 0.0886069563539
EfM3.000030 42 7 0.056022957147
EfM3.000040 8 3 0.747030568139
EfM3.000050 206 41 0.000156254234974
EfM3.000060 202 77 0.98242399106
EfM3.000070 129 96 4.27903239988e-07
EfM3.000080 89 55 0.00515772444784
EfM3.000090 11 5 0.953739963641
EfM3.000100 326 115 0.540509882575
EfM3.000110 149 52 0.664651068094
EfM3.000120 51 12 0.173877004922
EfM3.000140 5 1 0.891834856664
EfM3.000150 77 40 0.126856266567
EfM3.000160 66 27 0.825760718011
EfM3.000170 120 25 0.00741827440123
EfM3.000180 14 5 0.885850488021
EfM3.000190 1060 131 4.19300533687e-39
EfM3.000200 57 28 0.313028248106
EfM3.000210 876 129 2.43513831545e-26
EfM3.000220 1 2 0.382158317875
EfM3.000230 24 5 0.30414354427
EfM3.000240 67 32 0.33219737223
EfM3.000250 4 3 0.625379155452
EfM3.000260 14 10 0.183763552172
EfM3.000270 174 63 0.812324650242
EfM3.000280 6 1 0.719902357915
EfM3.000290 68 46 0.00286237630215
EfM3.000300 24 18 0.0392129256939
EfM3.000310 85 39 0.37169474

In [315]:
from statsmodels.stats import multitest

In [352]:
def read_count_sig(dict_a, dict_b): #makes pandas dataframe. might want to rename this?
#input gene name, dictionaries to look up gene name, do chi square. output tuple of gene name,
#pvalue (keep this in so we can correct for multiple testing later), 'significant/not'
    total_read_count_a = sum(dict_a.values())
    total_read_count_b = sum(dict_b.values())
    output_data = []
    for gene in dict_a.keys():
        if gene in dict_b.keys():
            count_a = dict_a[gene]
            count_b = dict_b[gene]
        if (count_a == 0) and (count_b == 0):
            #do something with genes with no read counts
            #currently skipping.
            pass
        else:
            contingency_table = np.array([[count_a, (total_read_count_a - count_a)], [count_b, (total_read_count_b - count_b)]])
            chi2_output = chi2_contingency(contingency_table)
            #print(gene, count_a, count_b, chi2_output[1])
        output_data.append(chi2_output[1])
    return(output_data)

In [354]:
pvals = read_count_sig(sample_a_dict, sample_b_dict)

In [343]:
L = []

In [345]:
for i in range(10):
    L.append(i)

In [340]:
#dataframe ramblings
                
            data = [gene, count_a, count_b, chi2_output[1]]
            pd_output_data = pd.DataFrame(data, columns=['Gene_Name', 'SampleA_Read_Count', 'SampleB_Read_Count', 'pvalue'])
            print(pd_output_data)

IndentationError: unexpected indent (<ipython-input-340-e429340703a2>, line 3)

In [346]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [356]:
from statsmodels.stats.multitest import multipletests
#calculate adjusted pvalues with statsmodels
multipletests(pvals, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

(array([False, False, False, False,  True, False,  True,  True, False,
        False, False, False, False, False, False, False,  True, False,
         True, False,  True, False, False, False, False, False, False,
        False,  True, False, False, False, False, False, False,  True,
        False,  True, False,  True, False, False,  True,  True, False,
         True, False, False, False, False,  True,  True, False, False,
        False, False,  True, False,  True, False,  True, False, False,
        False,  True, False,  True, False, False, False, False, False,
        False,  True,  True, False, False, False,  True, False, False,
        False,  True, False, False, False, False,  True,  True, False,
        False, False,  True, False, False,  True,  True, False, False, False], dtype=bool),
 array([  9.49833754e-01,   2.10968944e-01,   1.40057393e-01,
          8.78859492e-01,   8.22390710e-04,   9.97409969e-01,
          3.56586033e-06,   1.98374017e-02,   9.83237076e-01,
          7.